// by-vue/src/components/TImeSetter.vue
<template>
  <section class="time-setter">
    <template v-for="(item, index) in selectMap">
      <select
        :key="item.key"
        @change="
          (e) => {
            selectChangeHandler(item.key, e.target.value)
          }
        "
      >
        <option
          :selected="value[item.key] === idx"
          v-for="(n, idx) in item.max"
          :key="idx"
          :value="idx"
          >{{ idx }}
        </option>
      </select>
      <b class="text" :key="`text-${index}`">{{ item.text }}</b>
    </template>
    <slot></slot>
  </section>
</template>  
<script>
import utils from "../common/utils"

export default {
  props: {
    maxHour: {
      default: 24,
    },
    maxMinute: {
      default: 60,
    },
    maxSecond: {
      default: 60,
    },
    value: {},
  },
  data() {
    return {
      nowInfo: {
        ...{},
        ...this.value,
      },
    }
  },
  methods: {
    selectChangeHandler(key, value) {
      this.nowInfo[key] = Number(value)

      this.$emit("input", this.nowInfo)
    },
  },
  computed: {
    selectMap() {
      return [
        {
          key: "h",
          max: this.maxHour + 1,
          text: "时",
        },
        {
          key: "m",
          max: this.maxMinute + 1,
          text: "分",
        },
        {
          key: "s",
          max: this.maxSecond + 1,
          text: "秒",
        },
      ]
    },
  },
  mounted() {},
}
</script>
<style lang="less" scoped>
.text {
  margin: 0 10px;
}
</style>

// by-react/src/components/time_setter/index.js
import React, { Fragment } from "react"

import "./index.scss"

const TimeSetter = ({
  maxHour = 24,
  maxMinute = 60,
  maxSecond = 60,
  onChange,
  children,
  info = {
    h: 0,
    m: 0,
    s: 0,
  },
}) => {
  const selectMap = [
    {
      key: "h",
      max: maxHour + 1,
      text: "时",
    },
    {
      key: "m",
      max: maxMinute + 1,
      text: "分",
    },
    {
      key: "s",
      max: maxSecond + 1,
      text: "秒",
    },
  ]

  let nowInfo = {
    ...{},
    ...info,
  }

  const onChangeHandler = (e, key) => {
    nowInfo[key] = Number(e.target.value)
    onChange && onChange(nowInfo)
  }

  return (
    <section className="time-setter">
      {selectMap.map((item, index) => {
        return (
          <Fragment key={item.key}>
            <select
              onChange={(e) => {
                onChangeHandler(e, item.key)
              }}
              value={info[item.key]}
            >
              {new Array(item.max).fill("").map((n, idx) => {
                return (
                  <option key={idx} value={idx}>
                    {idx}
                  </option>
                )
              })}
            </select>
            <b className="text">{item.text}</b>
          </Fragment>
        )
      })}
      {children}
    </section>
  )
}

export default TimeSetter
