// by-vue/src/components/TimeDisplay.vue
<template>
  <span class="time-display">{{ fomatedDate }}</span>
</template>

<script>
import utils from "../common/utils"
export default {
  name: "TimeDisplay",
  props: {
    date: {
      default: 0,
    },
  },
  computed: {
    fomatedDate() {
      const info = utils.parseDate(this.date)
      return `${info.flag}${info.h}:${info.m}:${info.s}`
    },
  },
}
</script>
<style></style>

// by-react/src/components/TimeDisplay/index.js
import React from "react"
import utils from "../../common/utils"

import "./index.scss"

const TimeDisplay = ({ date = null }) => {
  if (typeof date !== "number" && !(date instanceof Date)) {
    return "--"
  }
  const info = utils.parseDate(date, true)

  return (
    <span className="time-display">{`${info.flag}${info.h}:${info.m}:${info.s}`}</span>
  )
}

export default TimeDisplay
