// by-vue/src/components/TimeDisplay.vue
<template>
  <span class="time-display">{{ fomatedDate }}</span>
</template>

<script>
import utils from "../common/utils"
export default {
  name: "TimeDisplay",
  props: {
    date: {
      default: 0,
    },
  },
  computed: {
    fomatedDate() {
      const info = utils.parseDate(this.date)
      return `${info.flag}${info.h}:${info.m}:${info.s}`
    },
  },
}
</script>
<style></style>

// by-react/src/components/time_display/index.js
import React from "react"
import utils from "../../common/utils"

import "./index.scss"

const TimeDisplay = ({ date = 0 }) => {
  const info = utils.parseDate(date)
  console.log("info ",info)
  return (
    <span className="time-display">{`${info.flag}${info.h}:${info.m}:${info.s}`}</span>
  )
}

export default TimeDisplay
